### ISSUE TITLE
Feature Request - Add "currentsummationreceived"

### ISSUE THREAD

**Issue by sprouse** [thevoltagesource/eagle-mqtt-bridge#4]
Thank you for releasing this bridge process. It has been the perfect piece of glue logic for my legacy Eagle-200 due to intermittent lock up of the local API, as well as general problems with Rainforest's legacy Portal not being reliable.

I have solar panels that generate energy. I have not observed the "currentsummationdelivered" value decrease when the solar array is producing energy.

Would it be possible to add the "currentsummationreceived" value as well and update the docker container?

**Comment by thevoltagesource** [comment]
It looks like the ```currentsummationdelivered``` message that I am breaking out has a ```delivered``` field and a ```received``` field.  ```Delivered``` matched the reading on my meter so that was an easy one to break out, but since I don't have anything feeding back to the grid ```received``` was always zero and I ignored it. According to the manual this should be the data you are looking for. I will break that out into its own MQTT topic and we will find out.  

Comparing the API manuals for the Eagle 100 and Eagle 200 there looks to be some potential differences in the message types.  If you find other things missing or not as you expect, just let me know.  There are several messages that the listener captures and ignores.  This is mostly because I didn't need that data for what I was doing, but maybe you or others would find this useful.  It is also possible I am not capturing some messages since there are differences between 100 and 200.

I'm glad you find this useful. It is cool to see others making use of my projects.

**Comment by sprouse** [comment]
I was actually able to modify the code to get the info I want. But I'm not sure if you would want to pick up my changes.
For one, I wanted to get a few more digits of resolution in the  energy  delivered/received fields.

I'll create a pull request so you can see the changes I made.

I multiplied the return value by 1000. Not sure if it would be possible to return a float instead?

**Comment by thevoltagesource** [comment]
Thanks for the PR, it helped me understand the request better.  I have added the summation received value to the messages.  I personally prefer the summation values in kWh but I can understand the desire to see more resolution so I created an environment variable to switch to Watt Hours (Wh).  

The new docker container (tag 0.9.1 or latest) has been pushed to Docker Hub.  Let me know if everything looks good.

**Comment by sprouse** [comment]
Thanks so much.
I’ll check it out tonight.

Again, this code has breathed new life in to my Eagle-200. 
It simultaneously solves the local API lockup problem and the fact that the legacy Portal is now unreliable.

By the way, are you using Home Assistant as well?

Cheers,
Steven

**Comment by thevoltagesource** [comment]
I am using Home Assistant.  I had the same issue with the local API dying on my Eagle 100.  I had found someone else's bridge solution but it was part of a bigger python automation project. I wanted something light weight I could run in a container so I wrote my own.

**Comment by sprouse** [comment]
Hi Jacob,
I was able to try out the updated code on my Eagle-200 and it is working.
The only feedback I have is that when I first started it I forgot to specify the SUMMATION_WATTS environment variable and I got this error:

/app/eagle-listener.js:8
const hires = process.env.SUMMATION_WATTS.toUpperCase() === 'TRUE' ? true : false
                                          ^

TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.<anonymous> (/app/eagle-listener.js:8:43)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/bridge.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ***@***.*** start: `node bridge.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ***@***.*** start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

After I added this and set it to “true” the container came up fine.
So people who may want to the default behavior may still need to define the variable.

Cheers,
Steven

**Comment by thevoltagesource** [comment]
Thank you for pointing that out.  I guess I never tested without the variable defined.  I will create a new issue.

Glad it is working for you.
