### ISSUE TITLE
Adding other data fields

### ISSUE THREAD

**Issue by kozoke** [thevoltagesource/eagle-mqtt-bridge#8]
Hi.  Great work on this project!

wrt: Details of most Eagle messages are in the code and can be used to enable additional published data.

I'm trying to add in price and tier.  I'm a noob so i'm likely missing some simple step.
Could you point me to some guidance on how to modify the correct files?  Here is what I did in the listener file.
Thanks!

 ```
   case 'pricecluster':                             
      var price = msg.price[0]                         
      var tier = msg.tier[0]                              
      //{ devicemacid: [ '0xd8d5b90000003e58' ],                                                  
      //  metermacid: [ '0x00078100001d2c64' ],               
      //  timestamp: [ '0xffffffff' ],                                                                                     
      //  price: [ '0x00000048' ],                          
      //  currency: [ '0x0348' ],                                                                                        
      //  trailingdigits: [ '0x03' ],                
      //  tier: [ '0x01' ],                                
      //  starttime: [ '0xffffffff' ],                       
      //  duration: [ '0xffff' ],                                                                 
      //  ratelabel: [ 'Set by User' ],                       
      //  port: [ '/dev/ttySP0' ] }                                                                                        
      var message = {'meter/price': price, 'meter/price': tier}   
```

Error based on this change:
```
at processMessage (/app/eagle-listener.js:162:57)
at /app/eagle-listener.js:22:6
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at next (/app/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at /app/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
at next (/app/node_modules/express/lib/router/index.js:275:10)
at responseHandler (/app/node_modules/express-xml-bodyparser/lib/types/xml.js:64:9)
```

**Comment by thevoltagesource** [comment]
Glad you like the project.  You are on the right track, you just need to pull from one level deeper in the json. The first line I added grabs the priceinfo node of the json data, from there we can grab the data fields you are wanting.   You probably prefer the number for price/tier in base 10 instead of base 16 so I used parseInt to convert. Let me know if this works.  I don't remember if my meter provides price messages or not, but I can run a test build tonight or tomorrow and verify this code doesn't crash on me.

 ```
   case 'pricecluster':
      var node = msg.pricecluster[0]
      var price = parseInt(node.price[0], 16)
      var tier = parseInt(node.tier[0], 16)
      //{ devicemacid: [ '0xd8d5b90000003e58' ],
      //  metermacid: [ '0x00078100001d2c64' ],
      //  timestamp: [ '0xffffffff' ],
      //  price: [ '0x00000048' ],
      //  currency: [ '0x0348' ],
      //  trailingdigits: [ '0x03' ],
      //  tier: [ '0x01' ],
      //  starttime: [ '0xffffffff' ],
      //  duration: [ '0xffff' ],
      //  ratelabel: [ 'Set by User' ],
      //  port: [ '/dev/ttySP0' ] }
      var message = {'meter/price': price, 'meter/price': tier}
      break
```

**Comment by thevoltagesource** [comment]
I realized I never created the docker build with the price data enabled so I have fixed that and you will find it with tag 0.9.3-price.  I receive price messages from my meter but it is just the value ```1```.  Hopefully you are getting useful data.  Let me know if you need any other help with this.

**Comment by thevoltagesource** [comment]
@kozoke did you get this working?  I would like to close this issue if this has been resolved.

**Comment by kozoke** [comment]
Hi. Sorry I forgot to respond. 
Yes, I just pulled the docker and I am receiving data.  When I compare it, the price is showing 3 (which is consistent with the 'tier' data i'm getting from the other similar container i'm running and the pge website.  The price data from the eagle website is  0.0000 but the price field is an integer.  Thoughts?  Thank you again for following up and adding the field.

**Comment by thevoltagesource** [comment]
That would be my fault.  Apparently I was pushing both the tier and price values to the same topic.  I just pushed a new docker image with the fix (1.1.0).  Pricing info is now published to ```MQTT_TOPIC/pricing/price``` and ``MQTT_TOPIC/pricing/tier```. The price value comes across as a number which I assume needs to be divided by 10 to get the appropriate decimal value.  Since I don't have pricing data provided by my utility I can't test this so let me know if you are getting what is expected.

**Comment by kozoke** [comment]
Thanks! Yes, that worked as you descried.  Appreciate the help!
![image](https://user-images.githubusercontent.com/14950116/120912847-874ed400-c647-11eb-91dd-0ad8ab6e22ad.png)

**Comment by thevoltagesource** [comment]
Cool.  Looking at the API specs, the price message also contains a field which is 'The number of implicit decimal places in the price. (e.g. 2 means divide Price by 100).'  Would you find it more useful to expose that field separately or should I do the math on the bridge side so you get the result like the image on the right?

**Comment by kozoke** [comment]
Hi. My preference would be to do the math on the bridge side so the result is readily consumable.  Thanks again for your help.

**Comment by thevoltagesource** [comment]
I had someone contribute an update that addressed the price being adjusted properly as reported by the meter. My efforts failed since my meter doesn't provide valid pricing data.  Give 1.2.0 a test when you have time and see if the price is correct for you as well.
